language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-8.0
      env:
        - MATRIX_EVAL="CC=gcc-8.0 && CXX=g++-8.0"

script:
  - mkdir -p build/run
  - cd build/run
  - cmake ../..
  - make install
  - cd ../..
